export const SEARCH_BAR_HEIGHT = 40;
export const PADDING_TOP_BAR = 16;
export const HEADER_FULL_HEIGHT = 300;
export const HEADER_MIN_HEIGHT = 100 + SEARCH_BAR_HEIGHT + PADDING_TOP_BAR;
export const HEADER_SCROLL_DISTANCE = HEADER_FULL_HEIGHT - HEADER_MIN_HEIGHT;
